language: php
php:
    - 5.3.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

script:
    - vendor/bin/tester tests -s -c tests/php-unix.ini
    - php code-checker/src/code-checker.php -d Nette

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester
    - travis_retry composer install --no-interaction --prefer-dist
    - travis_retry composer create-project nette/code-checker code-checker ~2.5 --no-interaction

git:
    depth: 10

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
